name: The Engage Group
#url: http://jayperryworks.github.io
baseurl: 

markdown: redcarpet
pygments: true

exclude: ["README.md", "codekit-config.json", "engage.sublime-project", "engage.sublime-workspace", "Gemfile", "Gemfile.lock", "Guardfile"]