name: The Engage Group
#url: http://jayperryworks.github.io
baseurl: 

markdown: redcarpet
pygments: true

exclude: ["README.md", "config.rb", ".sublime-project", ".sublime-workspace", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache"]